const $=id=>document.getElementById(id), token=document.querySelector('meta[name=trial-token]').content;
let rawRows=[], prepared=null, fileName='', workbook=null, busy=false;
const fmt=n=>Number(n).toLocaleString('th-TH'), money=n=>(n/100).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
function message(s,error=false){$('message').textContent=s;$('message').classList.toggle('error',error);}
function lock(value){busy=value;for(const id of ['inspect','demo','save','platform','business','file','sheet']) $(id).disabled=value;$('inspect').disabled=value||!rawRows.length;}
async function api(path,body){const res=await fetch('/trial/'+path,{method:body?'POST':'GET',headers:{'x-trial-token':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
function sorted(v){if(Array.isArray(v))return v.map(sorted);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sorted(v[k])]));return v;}
async function hash(v){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(sorted(v))));return [...new Uint8Array(bytes)].map(v=>v.toString(16).padStart(2,'0')).join('');}
function clearPreview(){prepared=null;$('preview').hidden=true;}
function table(rows){$('sample').replaceChildren();for(const r of rows){const tr=document.createElement('tr');for(const i of [1,3,7,9,11,12]){const td=document.createElement('td');td.textContent=r[i]||'—';tr.append(td);}$('sample').append(tr);}}
async function inspect(){lock(true);clearPreview();message('กำลังตรวจรูปแบบไฟล์และคำนวณยอด…');try{prepared=await api('parse',{rows:rawRows,platform:$('platform').value,business:$('business').value,fileName});const s=prepared.summary;$('summary').textContent=`${fileName} · ${fmt(s.rows)} รายการ · ${money(s.cents)} บาท · ${fmt(s.units)} ชิ้น`;$('warning').textContent=`ยังไม่มี SKU กลาง ${fmt(s.unmapped)} แถว · ไม่รวมสถานะยกเลิก/คืน ${fmt(s.excluded)} แถวในยอด หากคอลัมน์ยอดเงินไม่ใช่ยอดต่อรายการ กรุณาตรวจไฟล์ก่อนนำเข้า`;table(prepared.sample);$('preview').hidden=false;message('ตรวจรูปแบบผ่านแล้ว ตรวจตัวอย่างและยอดก่อนกดนำเข้าฐานทดลอง');}catch(e){message(e.message,true);}finally{lock(false);}}
function sheetRows(){const name=$('sheet').value;const grid=XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,raw:false,defval:''});const headers=(grid[0]||[]).map(x=>String(x).trim());const present=headers.filter(Boolean);if(new Set(present.map(h=>h.toLowerCase())).size!==present.length)throw new Error('มีชื่อคอลัมน์ซ้ำในแผ่นงาน กรุณาตรวจไฟล์');rawRows=grid.slice(1).filter(r=>r.some(x=>String(x).trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??'']).filter(([h])=>h)));if(rawRows.length>100000)throw new Error('จำกัด 100,000 แถวต่อไฟล์ทดลอง');$('inspect').disabled=!rawRows.length;clearPreview();message(`อ่าน ${fmt(rawRows.length)} แถว จากแผ่นงาน ${name} แล้ว กดตรวจไฟล์ต่อได้`);}
$('file').onchange=async()=>{clearPreview();rawRows=[];$('inspect').disabled=true;const file=$('file').files[0];if(!file)return;fileName=file.name;try{if(file.size>20_000_000)throw new Error('จำกัดไฟล์ 20 MB ต่อครั้งในหน้าทดลอง');if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(await file.text());if(!Array.isArray(data.values)||!Array.isArray(data.values[0]))throw new Error('JSON ต้องเป็น snapshot ที่มี values และหัวคอลัมน์');rawRows=data.values.slice(1).map(r=>Object.fromEntries(data.values[0].map((h,i)=>[h,r[i]??''])));$('sheetLabel').hidden=true;$('inspect').disabled=!rawRows.length;message(`อ่าน snapshot ${fmt(rawRows.length)} แถวแล้ว ต้องเป็นแพลตฟอร์มและธุรกิจเดียวกับที่เลือก`);}else{workbook=file.name.toLowerCase().endsWith('.csv') ? XLSX.read(await file.text(),{type:'string',raw:true}) : XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});$('sheet').replaceChildren(...workbook.SheetNames.map(n=>new Option(n,n)));$('sheetLabel').hidden=false;sheetRows();}}catch(e){rawRows=[];message(e.message,true);}};
$('sheet').onchange=()=>{try{sheetRows();}catch(e){message(e.message,true);}};
for(const id of ['platform','business'])$(id).onchange=clearPreview;
$('inspect').onclick=inspect;
$('demo').onclick=()=>{$('platform').value='Shopee';fileName='ข้อมูลสมมติ — ไม่ใช่ออเดอร์จริง';rawRows=[{order_id:'DEMO-001',date:'2026-08-01',product_name:'สินค้าสมมติ A',qty:'1',revenue:'100',order_status:'completed',sku_platform:'DEMO-A'},{order_id:'DEMO-001',date:'2026-08-01',product_name:'สินค้าสมมติ B',qty:'2',revenue:'250',order_status:'completed',sku_platform:'DEMO-B'}];inspect();};
$('save').onclick=async()=>{if(!prepared||busy)return;lock(true);try{const rows=prepared.rows,digest=await hash(rows),chunks=[];for(let i=0;i<rows.length;i+=500)chunks.push(rows.slice(i,i+500));const {id}=await api('create',{requestKey:digest,manifest:{platform:$('platform').value,business:$('business').value,parserVersion:'sheet-v3',expectedRows:rows.length,expectedChunks:chunks.length,payloadHash:digest}});const prior=(await api('state')).uploads.find(u=>u.id===id);if(prior?.status==='complete'){message('ล็อตนี้เคยนำเข้าแล้ว ไม่มีการเพิ่มยอดซ้ำ');await refresh();return;}for(let i=0;i<chunks.length;i++){message(`ส่งเข้าพื้นที่พัก ${i+1}/${chunks.length} ชุด ยังไม่เปลี่ยนยอดในฐานทดลอง`);await api('chunk',{id,index:i,rows:chunks[i]});}message('รับครบแล้ว กำลังตรวจและบันทึกฐานทดลอง…');const r=await api('finalize',{id});message(`สำเร็จเฉพาะฐานทดลอง: เพิ่ม ${fmt(r.inserted)} · อัปเดต ${fmt(r.updated)} · ไม่เปลี่ยน ${fmt(r.unchanged)} รายการ`);await refresh();}catch(e){message(e.message+' · หากส่งไม่ครบ กดนำเข้าอีกครั้งเพื่อส่งต่อได้',true);await refresh().catch(()=>{});}finally{lock(false);}};
const states={receiving:'รอรับ/บันทึก',complete:'สำเร็จ',blocked:'ต้องตรวจไฟล์',undone:'ย้อนล็อตแล้ว'};
async function refresh(){const data=await api('state');$('totalRows').textContent=fmt(data.totals.rows);$('totalMoney').textContent=money(data.totals.cents);$('totalUnits').textContent=fmt(data.totals.units);$('history').replaceChildren();if(!data.uploads.length){$('history').textContent='ยังไม่มีล็อตนำเข้า เลือกไฟล์หรือใช้ข้อมูลสมมติด้านบนเพื่อเริ่มทดลอง';return;}for(const u of data.uploads){const div=document.createElement('div');div.className='lot';const label=document.createElement('div');label.textContent=`${states[u.status]||u.status} · ${u.manifest.platform} / ${u.manifest.business} · รับแล้ว ${fmt(u.receivedRows)}/${fmt(u.manifest.expectedRows)} แถว`;const small=document.createElement('small');small.textContent=`ล็อต ${u.id}${u.errorCode?' · '+u.errorCode:''}`;label.append(small);div.append(label);if(u.status==='receiving'&&u.receivedChunks.length===u.manifest.expectedChunks&&u.receivedRows===u.manifest.expectedRows){const b=document.createElement('button');b.className='secondary';b.textContent='บันทึกล็อตที่รับครบ';b.onclick=async()=>{b.disabled=true;try{const r=await api('finalize',{id:u.id});message(`บันทึกแล้ว เพิ่ม ${r.inserted} อัปเดต ${r.updated} รายการ`);await refresh();}catch(e){message(e.message,true);await refresh();}};div.append(b);}$('history').append(div);}}
$('refresh').onclick=()=>refresh().catch(e=>message(e.message,true));refresh().catch(e=>message(e.message,true));
