import snapshot from '../data/sellerAdsSnapshot.json'
import './SellerAdsReports.css'
const d = snapshot.data

const num = value => value == null ? 'ไม่มีข้อมูล' : Number(value).toLocaleString('th-TH',{maximumFractionDigits:2})
const money = value => value == null ? 'ไม่มีข้อมูล' : num(value)+' บาท'
const percent = value => value == null ? 'ไม่มีข้อมูล' : num(value)+'%'
function Card({title,children}) {return <section className="report-card payi-glass-card"><h3>{title}</h3>{children}</section>}
function Table({headers,rows,label}) {return <div className="seller-ads-table"><table aria-label={label}><thead><tr>{headers.map((h,i)=><th scope="col" key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((value,j)=><td key={j}>{value ?? 'ไม่มีข้อมูล'}</td>)}</tr>)}</tbody></table></div>}
function Source({id}) {const source=d.DATA_SOURCES[id];return <p className="seller-ads-note">ที่มา: {source.method} · เก็บ {source.lastUpdated}</p>}
export default function SellerAdsReports() {
  const t = d.TIKTOK_MONTHLY.at(-1)
  return <section className="seller-ads-reports" aria-label="รายงานโฆษณาจาก Seller Center">
    <h2>Seller Center · Ads / ROAS</h2><p className="seller-ads-note">ข้อมูลบันทึกจาก topsecret · รายเดือน ส.ค. เก็บ 8 ก.ย. 2026 · คงค่าใช้จ่ายและ ROAS / ROI ตามแพลตฟอร์ม ไม่บวก VAT เพิ่ม · ไม่รวมกับค่าแอดที่กรอกใน Ops</p><Card title="โฆษณารายเดือน · ส.ค. 2026"><p className="muted small">อ่านจากรายงานโฆษณาของแพลตฟอร์ม · เก็บ {t.collectedOn} · Attribution window ไม่ได้ระบุ · TikTok GMV Max อาจให้เครดิตยอด organic ด้วย</p><Table label="โฆษณาเดือนสิงหาคม" headers={['แพลตฟอร์ม', 'ค่าโฆษณา', 'ยอดที่โฆษณาให้เครดิต', 'ROAS / ROI ที่รายงาน']} rows={d.SHOPEE_MONTHLY.map(s => ['Shopee', money(s.shopeeAds.spend),money(s.shopeeAds.attributedSales),num(s.shopeeAds.roas)]).concat([['TikTok',money(t.gmvMaxAds.spend),money(t.gmvMaxAds.attributedRevenue),num(t.gmvMaxAds.roi)]])} /></Card>
    <Card title="TikTok GMV Max · รายแคมเปญเดือนสิงหาคม"><Table label="GMV Max campaigns" headers={['แคมเปญ', 'ค่าโฆษณา', 'ยอดที่ให้เครดิต', 'ROI ที่รายงาน', 'เป้าหมาย ROI']} rows={t.gmvMaxAds.campaigns.map(r => [r.name,money(r.spend),money(r.revenue),num(r.roi),num(r.targetRoi)])} /><p className="muted small">ค่า ROI คงตามตัวเลขที่จดจากแพลตฟอร์ม ยอดเงินที่ปัดเศษอาจหารกลับไม่ตรงกัน · ยังไม่ใช่ข้อสรุปให้เพิ่มงบ</p></Card>
    <details className="report-card"><summary>โฆษณาระดับสินค้า / กลุ่ม · ช่วง 24–31 ส.ค.</summary><p className="muted small">Shopee 24–30 ส.ค. / TikTok 24–31 ส.ค. · มีทั้งสินค้าและกลุ่มโฆษณา ไม่ใช่รายการสินค้าทั้งร้าน</p><Table label="SKU ads" headers={['แพลตฟอร์ม', 'สินค้า / แคมเปญ', 'ประเภท', 'ค่าโฆษณา', 'ยอดที่ให้เครดิต', 'ROAS / ROI']} rows={d.SKU_ADS.map(r => [r.platform,r.productName,r.grain,money(r.spend),money(r.attributedRevenue),num(r.roas ?? r.roi)])} /><details><summary>ยอดรวมร้านในช่วงเดียวกันและที่มาแต่ละรายการ</summary><Table label="Shop ad aggregates" headers={['ร้าน', 'ตั้งแต่', 'ถึง', 'ค่าโฆษณา', 'ยอดให้เครดิต', 'หมายเหตุ']} rows={Object.entries(d.SKU_ADS_SHOP_AGGREGATE).map(([p,r]) => [p,r.dateFrom,r.dateTo,money(r.spend),money(r.attributedRevenue),r.note])} />{[...new Set(d.SKU_ADS.map(r => r.source))].map(s => <p className="muted small" key={s}>{s}</p>)}</details></details>
    <details className="report-card"><summary>ความครอบคลุมของรายการโฆษณาช่วง 24–31 ส.ค.</summary><p className="muted small">คำนวณด้วย reconcileSkuAds ของ topsecret · ไม่รวม ad group ซ้ำกับสินค้า</p><Table label="Ad source coverage" headers={['แพลตฟอร์ม','แคมเปญที่จด / ทั้งหมด','ครอบคลุมค่าโฆษณา','ครอบคลุมยอดให้เครดิต','ข้อจำกัด']} rows={snapshot.derived.skuAdsCoverage.map(r=>[r.platform,`${r.sampledCount} / ${r.totalCampaigns}`,percent(r.spendCoveragePct),percent(r.revenueCoveragePct),r.gapNote||'ครอบคลุมตามเกณฑ์ของต้นทาง'])} /></details>
    <details className="report-card"><summary>ข้อมูลโฆษณาเดือนกรกฎาคม</summary><Source id="adsSpend" /><Table label="July ads" headers={['แพลตฟอร์ม', 'ประเภท', 'วันที่', 'ค่าโฆษณา', 'ยอดให้เครดิต', 'ออเดอร์ที่ให้เครดิต']} rows={d.ADS_SPEND.map(r => [r.platform,r.source,r.date,money(r.spend),money(r.attributedRevenue),num(r.attributedOrders)])} /></details><Card title="ตัวเลขที่ยังใช้สรุปไม่ได้"><p>CAC ยังจับคู่จำนวนออเดอร์โฆษณากับลูกค้าไม่ซ้ำไม่ได้ · กำไรยังขาดต้นทุนต่อ SKU · LTV ข้ามแพลตฟอร์มยังขาดรหัสลูกค้าเดียวกัน · ชุดข้อมูลนี้ไม่แสดงตัวเลขเหล่านี้เป็นศูนย์</p></Card>
  </section>
}
