'use client';
import {useEffect,useState,type FormEvent} from 'react';
interface Settings{connections:{id:string;webhook_route_id:string}[];events:{status:string;last_error:string|null;created_at:string}[];localConfiguration:boolean;sendEnabled:boolean;publicWebUrl:string;ai:{url:string|null;model:string|null}}
export default function SettingsPanel(){
 const[data,setData]=useState<Settings|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void fetch('/api/core/api/settings').then(async r=>{if(!r.ok)throw new Error('โหลดการตั้งค่าไม่ได้');setData(await r.json() as Settings);}).catch(e=>setMessage(String(e)));},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=new FormData(e.currentTarget);
  try{const body={accessToken:form.get('token'),channelSecret:form.get('secret'),lineUserId:form.get('user'),publicWebUrl:form.get('url'),enabled:form.get('enabled')==='on'};
   const response=await fetch('/api/core/api/settings/line',{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'mona'},body:JSON.stringify(body)});const result=await response.json() as {message?:string;webhookPath?:string};if(!response.ok)throw new Error(result.message??'บันทึกไม่ได้');setMessage((result.message??'บันทึกแล้ว')+' · '+(result.webhookPath??''));
  }catch(error){setMessage(error instanceof Error?error.message:'บันทึกไม่ได้');}finally{setBusy(false);}
 }
 return <div className="layout"><section className="card"><span className="eyebrow">DEDICATED PROCUREMENT BOT</span><h2>LINE Bot จัดซื้อ ตัวใหม่</h2><p>ใช้ Messaging API Channel แยกสำหรับจัดซื้อ บอทแจ้งสต็อกและบอทเดิมไม่เปลี่ยนแปลง</p>{data&&<form className="form" onSubmit={save}><label>Channel Access Token ของบอทใหม่<input name="token" type="password" autoComplete="off" required/></label><label>Channel Secret ของบอทใหม่<input name="secret" type="password" autoComplete="off" required/></label><label>LINE User ID ของผู้อนุมัติ<input name="user" required pattern="U[a-f0-9]{32}"/><small>ผู้รับนี้จะผูกสิทธิ์กับบัญชีผู้ดูแลที่กำลังตั้งค่า</small></label><label>URL เว็บจัดซื้อที่เข้าถึงได้จากมือถือ<input name="url" type="url" required defaultValue={data.publicWebUrl.startsWith('https:')?data.publicWebUrl:''}/><small>HTTPS origin ของเซิร์ฟเวอร์ที่คุณควบคุม ไม่ใช่ localhost</small></label><label className="row"><input name="enabled" type="checkbox"/>เปิดสรุปอัตโนมัติ 17:00 น. หลังเริ่มระบบใหม่</label><p><small>ระบบตรวจโควตาก่อนส่ง จำกัดไม่เกินเพดานฟรีที่ตั้งไว้ หากโควตาเต็มจะพักการส่ง สามารถเปิดรายการในเว็บได้เสมอ</small></p><button className="primary" disabled={busy||!data.localConfiguration}>{busy?'กำลังตรวจและบันทึก…':'ตรวจ Token และบันทึกบอทใหม่'}</button></form>}</section><section><div className="card"><h2>ความพร้อมของระบบ</h2>{data?<><p>LINE: {data.connections.length?'ตั้งค่า connection แล้ว':'ยังไม่ได้ตั้งค่าบอทใหม่'}</p><p>ส่งตามเวลา: {data.sendEnabled?'เปิด':'ปิด'}</p><p>AI ในเครื่อง: {data.ai.model??'ยังไม่กำหนดโมเดล'}</p><p>กำหนดเวลา: Asia/Bangkok</p><p>เครื่องต้องเปิดและรัน ops:start ในช่วง 17:00 น. หากเริ่มหลังเวลาจะจัดสรุปวันนั้นเมื่อเริ่มระบบ</p></>:<p>กำลังตรวจสถานะ…</p>}</div><div className="card"><h2>การส่งสรุปล่าสุด</h2>{data?.events.length?<ul>{data.events.map((e,i)=><li key={i}>{new Date(e.created_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})} · {e.status}{e.last_error?' · '+e.last_error:''}</li>)}</ul>:<p>ยังไม่มีสรุปที่เข้าคิว</p>}</div>{message&&<div className="notice" role="status">{message}</div>}</section></div>;
}
